In [37]:
#Import necessary packages:
import numpy as np
from NN import layers

#Import the data:
#stored separately and imported here
# as a matrix of X and a *column vector* for the y's
from data.data import X_train, y_train


#Wait for this stuff: not ready:
from NN.loss_function import BCE


### Define the `learning_rate`:

In [38]:
lr=0.03

### Define the `Linear` layer:

In [39]:
linear_layer = layers.Linear(num_features=X_train.shape[1], num_neurons=2)

### 1) Input data `X_train` to linear layer:

In [40]:
output = linear_layer.forward(X_train)
output

array([[0.50978123, 0.49021877],
       [0.50695932, 0.49304068],
       [0.50964524, 0.49035476],
       [0.5068233 , 0.4931767 ]])

In [41]:
#"predictions"
#assumed to be meaningless at first pass:
np.argmax(output,axis=1)

array([0, 0, 0, 0])

In [42]:
#actuals
y_train

array([[0],
       [1],
       [1],
       [0]])

### 2) Compute the Binary Cross Entropy Loss:

In [43]:
loss = BCE(y_true=y_train , y_pred = output)
loss

0.6932890492522941

### 3) Compute Gradients

 - The derivations of these gradients is completed in the readme

In [44]:
d_output = output - y_train
dz = d_output * (output) * (1-output)
d_weights = np.dot(X_train.T, dz)
d_bias = np.mean(dz , axis= 0)

### 4) Update the weights:

In [45]:
linear_layer.weights -= lr*d_weights
linear_layer.bias -= lr*d_bias

### 5) Repeat Steps 1 through 4 a large number of times.  Take note of how the loss function progresses and what happens to prediction accuracy after training is complete:

In [46]:
d_output - y_train

array([[ 0.50978123,  0.49021877],
       [-1.49304068, -1.50695932],
       [-1.49035476, -1.50964524],
       [ 0.5068233 ,  0.4931767 ]])

In [47]:
for epoch in range(100000):
    #STEP 1:
    output = linear_layer.forward(X_train)
    
    #STEP 2:
    loss = BCE(y_true=y_train , y_pred = output)
    
    #STEP 3:
    d_output = output - y_train
    d_weights = np.dot(X_train.T, dz)
    d_bias = np.mean(dz , axis= 0)
    
    #STEP 4:

    linear_layer.weights -= lr*d_weights
    linear_layer.bias -= lr*d_bias

    #Give periodic updates on the loss function:
    if epoch % 10000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")
        #weights gradient apppears to be getting stuck
        #print(f'd_weights at epoch {epoch}: {d_weights}')

Epoch 0, Loss: 0.6933
d_weights at epoch 0: [[ 0.00413916 -0.00409268]
 [ 0.00344594 -0.00344406]]
Epoch 10000, Loss: 0.6935
d_weights at epoch 10000: [[ 0.00413916 -0.00409268]
 [ 0.00344594 -0.00344406]]
Epoch 20000, Loss: 0.7572
d_weights at epoch 20000: [[ 0.00413916 -0.00409268]
 [ 0.00344594 -0.00344406]]
Epoch 30000, Loss: 0.7829
d_weights at epoch 30000: [[ 0.00413916 -0.00409268]
 [ 0.00344594 -0.00344406]]
Epoch 40000, Loss: 0.7829
d_weights at epoch 40000: [[ 0.00413916 -0.00409268]
 [ 0.00344594 -0.00344406]]
Epoch 50000, Loss: 0.7863
d_weights at epoch 50000: [[ 0.00413916 -0.00409268]
 [ 0.00344594 -0.00344406]]
Epoch 60000, Loss: 0.8104
d_weights at epoch 60000: [[ 0.00413916 -0.00409268]
 [ 0.00344594 -0.00344406]]
Epoch 70000, Loss: 0.8128
d_weights at epoch 70000: [[ 0.00413916 -0.00409268]
 [ 0.00344594 -0.00344406]]
Epoch 80000, Loss: 0.8128
d_weights at epoch 80000: [[ 0.00413916 -0.00409268]
 [ 0.00344594 -0.00344406]]
Epoch 90000, Loss: 0.8128
d_weights at epoch 

In [48]:
output

array([[0.26933483, 0.73066517],
       [0.26933483, 0.73066517],
       [0.26933483, 0.73066517],
       [0.26933483, 0.73066517]])

This is not ideal.  The network has learned $\begin{bmatrix}0.5 & 0.5\\0.5 & 0.5\\0.5 & 0.5\\0.5 & 0.5\end{bmatrix}$ when the actual outputs are $\begin{bmatrix}0\\1\\1\\0\end{bmatrix}$.  This may be due to choice of loss function, or not enough layers/neurons.