In [1]:
#Import necessary packages:
import numpy as np
from NN import layers

#Import the data:
#stored separately and imported here
# as a matrix of X and a *column vector* for the y's
from data.data import X_train, y_train


#Wait for this stuff: not ready:
from NN.loss_function import BCE


### Define the `learning_rate`:

In [2]:
lr=0.03

### Define the `Linear` layer:

In [3]:
linear_layer = layers.Linear(num_features=X_train.shape[1], num_neurons=2)

### 1) Input data `X_train` to linear layer:

In [4]:
output = linear_layer.forward(X_train)
output

array([[0.26933483, 0.73066517],
       [0.26933483, 0.73066517],
       [0.26933483, 0.73066517],
       [0.26933483, 0.73066517]])

In [5]:
#"predictions"
#assumed to be meaningless at first pass:
np.argmax(output,axis=1)

array([1, 1, 1, 1])

In [6]:
#actuals
y_train

array([[0],
       [1],
       [1],
       [0]])

### 2) Compute the Binary Cross Entropy Loss:

In [7]:
loss = BCE(y_true=y_train , y_pred = output)
loss

0.8127999637059493

### 3) Compute Gradients

 - The derivations of these gradients is completed in the readme

In [8]:
d_output = output - y_train
dz = d_output * (output) * (1-output)
d_weights = np.dot(X_train.T, dz)
d_bias = np.mean(dz , axis= 0)

### 4) Update the weights:

In [9]:
linear_layer.weights -= lr*d_weights
linear_layer.bias -= lr*d_bias

### 5) Repeat Steps 1 through 4 a large number of times.  Take note of how the loss function progresses and what happens to prediction accuracy after training is complete:

In [10]:
d_output - y_train

array([[ 0.26933483,  0.73066517],
       [-1.73066517, -1.26933483],
       [-1.73066517, -1.26933483],
       [ 0.26933483,  0.73066517]])

In [11]:
for epoch in range(100000):
    #STEP 1:
    output = linear_layer.forward(X_train)
    
    #STEP 2:
    loss = BCE(y_true=y_train , y_pred = output)
    
    #STEP 3:
    d_output = output - y_train
    d_weights = np.dot(X_train.T, dz)
    d_bias = np.mean(dz , axis= 0)
    
    #STEP 4:

    linear_layer.weights -= lr*d_weights
    linear_layer.bias -= lr*d_bias

    #Give periodic updates on the loss function:
    if epoch % 10000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")
        #weights gradient apppears to be getting stuck
        #print(f'd_weights at epoch {epoch}: {d_weights}')

Epoch 0, Loss: 0.8128
Epoch 10000, Loss: 0.8128
Epoch 20000, Loss: 0.8128
Epoch 30000, Loss: 0.8128
Epoch 40000, Loss: 0.8128
Epoch 50000, Loss: 0.8128
Epoch 60000, Loss: 0.8128
Epoch 70000, Loss: 0.8128
Epoch 80000, Loss: 0.8128
Epoch 90000, Loss: 0.8128


In [12]:
output

array([[0.73066517, 0.26933483],
       [0.73066517, 0.26933483],
       [0.73066517, 0.26933483],
       [0.73066517, 0.26933483]])

This is not ideal.  The network has learned $\begin{bmatrix}0.5 & 0.5\\0.5 & 0.5\\0.5 & 0.5\\0.5 & 0.5\end{bmatrix}$ when the actual outputs are $\begin{bmatrix}0\\1\\1\\0\end{bmatrix}$.  This may be due to choice of loss function, or not enough layers/neurons.